# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ledger.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import shared_pb2 as shared__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cledger.proto\x12\x03phi\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0cshared.proto\".\n\x0bSyncMessage\x12\x10\n\x08Username\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\"!\n\x10\x46ileChunkMessage\x12\r\n\x05\x43hunk\x18\x01 \x01(\x0c\x32\x94\x01\n\x12\x42\x65\x61nAccountService\x12\x36\n\nSyncLedger\x12\x10.phi.SyncMessage\x1a\x16.google.protobuf.Empty\x12\x46\n\x17\x44ownLoadBeanAccountFile\x12\x12.phi.StringMessage\x1a\x15.phi.FileChunkMessage0\x01\x42\x1cZ\x1agithub.com/clstb/phi/protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ledger_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\032github.com/clstb/phi/proto'
  _SYNCMESSAGE._serialized_start=64
  _SYNCMESSAGE._serialized_end=110
  _FILECHUNKMESSAGE._serialized_start=112
  _FILECHUNKMESSAGE._serialized_end=145
  _BEANACCOUNTSERVICE._serialized_start=148
  _BEANACCOUNTSERVICE._serialized_end=296
# @@protoc_insertion_point(module_scope)
