kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    username: clstb
    password:
      from_secret: docker_password
    repo: clstb/phi
    auto_tag: true
    dry_run: true
