kind: pipeline
name: default

services:
- name: db
  image: cockroachdb/cockroach:v20.2.4
  commands:
  - cockroach start-single-node --insecure

environment:
  DB: postgres://root@db:26257/defaultdb?sslmode=disable

steps:
- name: build
  image: golang:1.15.6-alpine
  commands:
  - apk add --no-cache git make protoc gcc musl-dev
  - make install-generators
  - make gen
  - make test-integration
  - make build
  
- name: docker  
  image: plugins/docker
  settings:
    username: clstb
    password:
      from_secret: docker_password
    repo: clstb/phi
    auto_tag: true

trigger:
  event:
  - push
