kind: pipeline
name: default

services:
- name: db
  image: cockroachdb/cockroach:v20.2.4
  commands:
  - cockroach start-single-node --insecure

environment:
  DB: postgres://root@db:26257/defaultdb?sslmode=disable

steps:
- name: docker  
  image: plugins/docker
  settings:
    username: clstb
    password:
      from_secret: docker_password
    repo: clstb/phi
    build_args:
    - test_tags=integration
