apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: phi
build:
  local:
    concurrency: 0
  artifacts:
    - image: ghcr.io/clstb/phi-auth
      ko:
        main: ./go/cmd/auth
      hooks:
        before:
          - command: [ "zsh", "-c", "make stubs_auth" ]
            os: [ darwin, linux ]
    - image: ghcr.io/clstb/phi-tinkgw
      ko:
        main: ./go/cmd/tinkgw
      hooks:
        before:
          - command: [ "zsh", "-c", "make stubs_tinkgw" ]
            os: [ darwin, linux ]
deploy:
  kustomize:
    paths:
      - k8s/local
portForward:
  - resourceType: deployment
    resourceName: phi-auth
    port: 8080
  - resourceType: deployment
    resourceName: phi-tinkgw
    port: 8080
