POST http://localhost:8081/api/register
Content-Type: application/json

{
  "username": "ass4",
  "password": "AnIu0RzcIl*o"
}

###

POST http://localhost:8081/api/login
Content-Type: application/json

{
  "username": "ass4",
  "password": "AnIu0RzcIl*o"
}
