POST http://localhost:8099/api/register
Content-Type: application/json

{
  "username": "ass1",
  "password": "AnIu0RzcIl*o"
}

###

POST http://localhost:8081/api/login
Content-Type: application/json

{
  "username": "artem",
  "password": "AnIu0RzcIl*o"
}

###
POST https://youthful-colden-lom8uboh9g.projects.oryapis.com/api/kratos/public/self-service/login?flow=7a54597e-039a-481b-b6e1-6a8402506296
Content-Type: application/json

{
  "username": "artem",
  "password": "AnIu0RzcIl*o"
}
