apiVersion: apps/v1
kind: Deployment
metadata:
  name: phi-auth
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  template:
    spec:
      initContainers:
        - image: clstb/phi
          name: phi-auth-migrate
          args: ["migrate", "auth"]
          envFrom:
            - secretRef:
                name: phi-auth
                optional: false
      containers:
        - image: clstb/phi
          name: phi-auth
          args: ["server",  "auth"]
          envFrom:
            - secretRef:
                name: phi-auth
                optional: false
          ports:
            - containerPort: 9000
              name: grpc
