apiVersion: apps/v1
kind: Deployment
metadata:
  name: phi-tinkgw
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  template:
    spec:
      containers:
        - image: clstb/phi-tinkgw
          name: phi-tinkgw
          args: ["server"]
          envFrom:
            - secretRef:
                name: phi-tinkgw
                optional: false
          ports:
            - containerPort: 9000
              name: grpc