# GET token
# curl -v https://api.tink.com/api/v1/oauth/token
#                -d 'code=9f556ac47def4ceeae65bc2ac6e330b1'
#                -d 'client_id=b534d4493183487e8e77ce3eeccaae1b'
#                -d 'client_secret=fcbdf733d6fd4c219dff0d728e2ae107'
#                -d 'grant_type=authorization_code'
POST https://api.tink.com/api/v1/oauth/token
Content-Type: application/x-www-form-urlencoded

code=b8dd713e146e40a58f5c39891bc0b6da&client_id=b534d4493183487e8e77ce3eeccaae1b&client_secret=fcbdf733d6fd4c219dff0d728e2ae107&grant_type=authorization_code

###

# curl https://api.tink.com/api/v1/providers
#-H 'Authorization: Bearer {YOUR TOKEN}'
GET https://api.tink.com/api/v1/providers
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6IjZkOTM3MGUyLWRhODItNDdkYy04MmU2LTg1YjBkMDhlOWU5OSIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTI2MzM4NjMsImlhdCI6MTY1MjYyNjY2MywiaXNzIjoidGluazovL2F1dGgiLCJqdGkiOiJkMGZlNjEzOS1kYjkyLTQ3NGUtYjIzOS04YjMyNWE4MWI3MmUiLCJvcmlnaW4iOiJtYWluIiwic2NvcGVzIjpbImJhbGFuY2VzOnJlYWQiLCJhY2NvdW50czpyZWFkIiwidHJhbnNhY3Rpb25zOnJlYWQiXSwic3ViIjoidGluazovL2F1dGgvdXNlci8yMmM1NmNhOTM3Y2Y0M2JjOTA3M2ZiZjZjZTI1YmFkZiIsInRpbms6Ly9hcHAvaWQiOiI1YzEwYjZjODMyNGU0Mjc1YTgzNjdlOTViMGI2NjFhZiIsInRpbms6Ly9hcHAvdmVyaWZpZWQiOiJmYWxzZSJ9.QduV3R_Gqv_zOYggJ9hc-XWNXaitjo29h67R4CraBplSkc3icRKhKXY2cpL67tHMLfR9s5iJdI0EEb2j0JeMKA

###

# curl https://api.tink.com/data/v2/transactions
#-H 'Authorization: Bearer {YOUR TOKEN}'
GET https://api.tink.com/data/v2/transactions
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6IjZkOTM3MGUyLWRhODItNDdkYy04MmU2LTg1YjBkMDhlOWU5OSIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTI2MzM4NjMsImlhdCI6MTY1MjYyNjY2MywiaXNzIjoidGluazovL2F1dGgiLCJqdGkiOiJkMGZlNjEzOS1kYjkyLTQ3NGUtYjIzOS04YjMyNWE4MWI3MmUiLCJvcmlnaW4iOiJtYWluIiwic2NvcGVzIjpbImJhbGFuY2VzOnJlYWQiLCJhY2NvdW50czpyZWFkIiwidHJhbnNhY3Rpb25zOnJlYWQiXSwic3ViIjoidGluazovL2F1dGgvdXNlci8yMmM1NmNhOTM3Y2Y0M2JjOTA3M2ZiZjZjZTI1YmFkZiIsInRpbms6Ly9hcHAvaWQiOiI1YzEwYjZjODMyNGU0Mjc1YTgzNjdlOTViMGI2NjFhZiIsInRpbms6Ly9hcHAvdmVyaWZpZWQiOiJmYWxzZSJ9.QduV3R_Gqv_zOYggJ9hc-XWNXaitjo29h67R4CraBplSkc3icRKhKXY2cpL67tHMLfR9s5iJdI0EEb2j0JeMKA

###

# curl https://api.tink.com/data/v2/accounts
#-H 'Authorization: Bearer {YOUR TOKEN}'
GET https://api.tink.com/data/v2/accounts
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6IjZkOTM3MGUyLWRhODItNDdkYy04MmU2LTg1YjBkMDhlOWU5OSIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTI2MzM4NjMsImlhdCI6MTY1MjYyNjY2MywiaXNzIjoidGluazovL2F1dGgiLCJqdGkiOiJkMGZlNjEzOS1kYjkyLTQ3NGUtYjIzOS04YjMyNWE4MWI3MmUiLCJvcmlnaW4iOiJtYWluIiwic2NvcGVzIjpbImJhbGFuY2VzOnJlYWQiLCJhY2NvdW50czpyZWFkIiwidHJhbnNhY3Rpb25zOnJlYWQiXSwic3ViIjoidGluazovL2F1dGgvdXNlci8yMmM1NmNhOTM3Y2Y0M2JjOTA3M2ZiZjZjZTI1YmFkZiIsInRpbms6Ly9hcHAvaWQiOiI1YzEwYjZjODMyNGU0Mjc1YTgzNjdlOTViMGI2NjFhZiIsInRpbms6Ly9hcHAvdmVyaWZpZWQiOiJmYWxzZSJ9.QduV3R_Gqv_zOYggJ9hc-XWNXaitjo29h67R4CraBplSkc3icRKhKXY2cpL67tHMLfR9s5iJdI0EEb2j0JeMKA

###








