// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"github.com/gofrs/uuid"
)

type Ledger struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	Data   []byte    `json:"data"`
	Dk     []byte    `json:"dk"`
}
