// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"

	"github.com/gofrs/uuid"
)

type Querier interface {
	CreateLedger(ctx context.Context, arg CreateLedgerParams) (Ledger, error)
	GetLedger(ctx context.Context, id uuid.UUID) (Ledger, error)
	UpdateLedger(ctx context.Context, arg UpdateLedgerParams) (Ledger, error)
}

var _ Querier = (*Queries)(nil)
