// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"github.com/gofrs/uuid"
)

type User struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Password []byte    `json:"password"`
}
