// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetUserByName(ctx context.Context, name string) (User, error)
}

var _ Querier = (*Queries)(nil)
