apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: phi-auth-db
spec:
  selector:
    matchLabels:
      app: db-auth
  serviceName: phi-auth-db
  replicas: 1
  template:
    metadata:
      labels:
        app: db-auth
    spec:
      containers:
      - image: postgres:13
        name: postgres
        env:
        - name: POSTGRES_PASSWORD
          value: phi_auth
        - name: POSTGRES_USER
          value: phi_auth
        ports:
          - containerPort: 5432
            name: postgres
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 1Gi