// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"

	"github.com/gofrs/uuid"
)

type Account struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

type Posting struct {
	ID          uuid.UUID `json:"id"`
	Account     uuid.UUID `json:"account"`
	Transaction uuid.UUID `json:"transaction"`
	Units       Amount    `json:"units"`
	Cost        Amount    `json:"cost"`
	Price       Amount    `json:"price"`
}

type Transaction struct {
	ID        uuid.UUID `json:"id"`
	Date      time.Time `json:"date"`
	Entity    string    `json:"entity"`
	Reference string    `json:"reference"`
	Hash      string    `json:"hash"`
}
